---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - knowledge.example.com
  resources:
  - snappyknowledges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - knowledge.example.com
  resources:
  - snappyknowledges/finalizers
  verbs:
  - update
- apiGroups:
  - knowledge.example.com
  resources:
  - snappyknowledges/status
  verbs:
  - get
  - patch
  - update
